Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: example.KinesisFirehoseEventHandler
      CodeUri: /Users/ibk/aws-lambda-java-libs/samples/kinesis-firehose-event-handler
      Runtime: java11
      Architectures:
        - x86_64